#! /usr/bin/bash

# Script to show data about Transmission

speeds=$(transmission-remote -l 2>/dev/null)

if [ -z "${speeds}" ]; then
	exit 1
fi

down=$(echo "${speeds}" | awk '$1~/Sum/ {print $5}' | awk -F. '{print $1}')

if [[ $down == 0 ]]; then
	printf ""
elif [[ $down -ge 1024 ]]; then
	down=$(echo "$down" | numfmt --to iec --format "%1.1f" --from-unit 1024)
	printf ' %s' "${down}"
else
	down=$(echo "$down" | numfmt --to iec --format "%3.0f" --from-unit 1024)
	printf ' %s' "${down}"
fi
